Linter Changes (#12)
* added synchronize to PR and excluded autogenerated code

* updated ignore list format

* change fail fast error

* removed CANOpen directories from linter

Removed them because we are moving away from CANOpen STM32

diff --git a/.github/workflows/cpp-linter.yml b/.github/workflows/cpp-linter.yml
--- a/.github/workflows/cpp-linter.yml
+++ b/.github/workflows/cpp-linter.yml
@@ -5,6 +5,7 @@ on:
       - opened
       - reopened
       - ready_for_review
+      - synchronize
 jobs:
   cpp-linter:
     runs-on: ubuntu-latest
@@ -18,7 +19,9 @@ jobs:
           style: 'file'
           tidy-checks: ''
           thread-comments: ${{ github.event_name == 'pull_request' && 'update' }}
-          ignore: 'CANopenNode/'
+          ignore: 'Drivers/|Middlewares/|SMBus_PMBus_Stack/'
       - name: Fail fast?!
         if: steps.linter.outputs.checks-failed > 0
-        run: exit 1
+        run: |
+          echo "::error::${{steps.linter.outputs.checks-failed}} Linting failed. Please fix before merging."
+          exit 1
